name = "albums"

[[album]]
album = "278593248"
name = "good-people-all"
title = "Good People All"

# ===============================

[[album]]
album = "3669717315"
name = "yuletide-live"
title = "Yuletide Live"

# ===============================

[[album]]
album = "1558635893"
name = "celtic-holiday-2cd-set"
title = "Celtic Holiday 2CD set"

# ===============================

[[album]]
album = "3669366765"
name = "celtic-yuletide-celebrating-31-years-live"
title = "Celtic Yuletide Celebrating 31 Years Live!"

# ===============================

[[album]]
album = "862198624"
name = "fairy-wind"
title = "Fairy Wind"

# ===============================

[[album]]
album = "627094978"
name = "where-dragons-dance"
title = "Where Dragons Dance"

# ===============================

[[album]]
album = "2523392139"
name = "legend-of-inishcahey"
title = "Legend of Inishcahey"

# ===============================

[[album]]
album = "2676296816"
name = "islands-calling"
title = "Islands Calling"

# ===============================

[[album]]
album = "4106561135"
name = "bell-off-the-ledge"
title = "Bell Off The Ledge"

# ===============================

[[album]]
album = "939499992"
name = "crossing-to-skellig"
title = "Crossing to Skellig"

# ===============================

[[album]]
album = "168053147"
name = "harp"
title = "Harp"

# ===============================

[[album]]
album = "2445474553"
name = "beneath-the-moon"
title = "Beneath The Moon"

# ===============================

[[album]]
album = "637018368"
name = "musings"
title = "Musings"

# ===============================

[[album]]
album = "1051416817"
name = "on-the-burren"
title = "On the Burren"

# ===============================

[[album]]
album = "1462145800"
name = "above-the-tower"
title = "Above the Tower"

# ===============================

[[album]]
album = "2879454663"
name = "spring-tide"
title = "Spring Tide"

# ===============================

[[album]]
album = "3755786809"
name = "lullaby-for-a-souls-journey"
title = "Lullaby for a Souls Journey"

# ===============================

[[album]]
album = "1127332636"
name = "longing-for-ireland"
title = "Loging For Irelane"

# ===============================

[[album]]
album = "131328515"
name = "dances-and-dreams-best-of-magical-strings-2cd-set"
title = "Dances and Dreams - Best of Magical Strings 2CD set"

# ===============================

[[album]]
album = "216506679"
name = "celtic-mist-2cd-set"
title = "Celtic Mist 2CD set"

# ===============================

[[album]]
album = "2516297162"
name = "elegance-of-hammered-dulcimer-2cd-set"
title = "Elegance of Hammered Dulcimer 2CD set"

# ===============================
